# sample: https://github.com/github/docs/blob/main/.github/workflows/link-check-all.yml
name:  static analysis
on:
  push:
  pull_request:

jobs:
  phpunit:
    name: PHP-${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - '7.4'
          - '8.0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: PHP version
        run: php -v

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: Run PHPStan
        run: composer phpstan

      - name: Run php cs fixer
        run: composer check-style
